version: '3.7'

services:
  app:
    image: 'springboot-docker-postgresql:latest'
    container_name: app
    build:
      context: .
    depends_on:
      - database
    env_file: .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/$DATABASE_NAME
      - SPRING_DATASOURCE_USERNAME=$DATABASE_USERNAME
      - SPRING_DATASOURCE_PASSWORD=$DATABASE_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
#    restart: always
  database:
    image: 'postgres:15-alpine'
    container_name: postgresdatabase
    env_file: .env
    environment:
      - POSTGRES_USER=$DATABASE_USERNAME
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - 5432:5432

